import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

// Translation object with all supported languages
const translations = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.profile': 'Profile',
    'nav.feed': 'Feed',
  'nav.communities': 'Communities',
  'nav.marketplace' : 'Market',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logo': 'Logo',
    
    // Sidebar
    'sidebar.title': 'Settings & More',
    'sidebar.user': 'User Account',
    'sidebar.welcome': 'Welcome',
    'sidebar.logout': 'Logout',
    'sidebar.loginToAccount': 'Login to your account',
    'sidebar.theme': 'Theme',
  'sidebar.darkMode': 'Dark Mode',
  'sidebar.lightMode': 'Light Mode',
    'sidebar.navigation': 'Navigation',
    'sidebar.configurations': 'Configurations',
    'sidebar.language': 'Language',
    
    // Home Page
    'home.welcome': 'Welcome to Our App',
    'home.welcomeBack': 'Welcome back',
    'home.getStarted': 'Get Started',
    'home.getStartedText': 'Ready to join us? Create an account or login to your existing account.',
    'home.signUp': 'Sign Up',
    'home.loginBtn': 'Login',
    'home.yourFeed': 'Your Personal Feed',
    'home.feedDescription': 'Stay updated with personalized content just for you.',
    'home.welcomeMessage': 'Great to see you again! Your personalized experience awaits.',
    'home.feedComingSoon': 'Feed content is being prepared. Check back soon for updates!',
    'home.quickActions': 'Quick Actions',
    'home.footer': '© 2025 Our App. All rights reserved.',
    
    // About/Features (moved from landing)
    'landing.about': 'About Us',
    'landing.aboutText': 'This is a simple landing page built with React. We provide amazing services and solutions for our users.',
    'landing.features': 'Features',
    'landing.feature1': 'Easy to use interface',
    'landing.feature2': 'Secure authentication',
    'landing.feature3': 'Fast and reliable',
    'landing.feature4': '24/7 support',
    
    // Feed Page
    'feed.title': 'Feed',
    'feed.description': 'Stay updated with the latest posts and activities from our community.',
    'feed.comingSoon': 'Feed content coming soon! This will show posts, updates, and community activities.',
    
    // About Page
    'about.title': 'About Our Company',
    'about.description': 'Learn more about our mission, values, and the team behind our innovative solutions.',
    'about.mission': 'Our Mission',
    'about.missionText': 'We are dedicated to providing cutting-edge technology solutions that empower businesses and individuals to achieve their goals. Our commitment to excellence drives everything we do.',
    'about.team': 'Our Team',
    'about.teamText': 'Our diverse team of experts brings together years of experience in technology, design, and customer service. We work collaboratively to deliver the best possible experience for our users.',
    
    // Login Page
    'login.title': 'Login',
    'login.email': 'Email:',
    'login.password': 'Password:',
    'login.loginBtn': 'Login',
    'login.noAccount': "Don't have an account?",
    'login.registerHere': 'Register here',
    
    // Register Page
    'register.title': 'Register',
    'register.firstName': 'First Name:',
    'register.lastName': 'Last Name:',
    'register.email': 'Email:',
    'register.password': 'Password:',
    'register.confirmPassword': 'Confirm Password:',
    'register.registerBtn': 'Register',
    'register.hasAccount': 'Already have an account?',
    'register.loginHere': 'Login here',
    
    // Form validation messages
    'validation.fillAllFields': 'Please fill in all fields',
    'validation.passwordsMismatch': 'Passwords do not match',
    'validation.passwordTooShort': 'Password must be at least 6 characters long',
    'validation.loginDemo': 'Login functionality would be implemented here',
    'validation.registerDemo': 'Registration functionality would be implemented here',
    
    // Profile Page
    'profile.aboutMe': 'About Me',
    'profile.details' : 'Details',
    'profile.interests': 'Interests',
    'profile.contact': 'Contact',
    'profile.leaveMessage': 'Leave a message',
    'profile.age': 'Age',
    'profile.status': 'Status',
    'profile.location': 'Location',
    'profile.occupation': 'Occupation',
    'profile.memberSince': 'Member since',
    'profile.single': 'Single',
    'profile.webDeveloper': 'Web Developer',
  // Relationship statuses (use keys as stable identifiers)
  'relationship.single': 'Single',
  'relationship.situationship': 'Situationship',
  'relationship.inRelationship': 'In a Relationship',
  'relationship.engaged': 'Engaged',
  'relationship.married': 'Married',
  'relationship.divorced': 'Divorced',
  'relationship.separated': 'Separated',
  'relationship.widowed': 'Widowed',
    
    // Profile Tabs
    'profile.kudos': 'Kudos',
    'profile.photos': 'Photos',
    'profile.friends': 'Friends',
    'profile.showMore': 'Show More',
    'profile.viewAll': 'View All',
  'profile.createNew': 'Create Community',
    'profile.totalPhotos': 'total photos',
  'profile.totalFriends': 'friends',
    'profile.totalMembers': 'members',
  'profile.contact': 'Contact',
  'profile.leaveMessage': 'Leave a message',
  'profile.message': 'Message',
  'profile.opening': 'Opening...',
  'profile.unfriend': 'Unfriend',
  'profile.removing': 'Removing...',
  'profile.addFriend': 'Add Friend',
  'profile.sending': 'Sending...',
  'profile.edit': 'Edit',  // Gallery
  'gallery.backToProfile': '← Back to {name}\'s Profile',
  'gallery.photosTitle': '{name}\'s Photos',
  'gallery.photosCount': '{count} photos',
    
    // Community Model (public, member-only posting, join requests)
    'community.publicViewable': 'Anyone can view this community',
    'community.membersPost': 'Only members can post',
    'community.requestJoin': 'Request to join',
    'community.joinSent': 'Join request sent',
    'community.waitingApproval': 'Waiting for approval',
    'community.youAreMember': 'You are a member',
    'community.postThread': 'Post a thread',
    'community.join': 'Join',
    'community.leave': 'Leave',
    'community.joined': 'Joined',
    'community.notMember': 'You are not a member',
    'community.membersOnly': 'Members only',
    'community.approvalRequired': 'Approval required to join',
    'community.joinError': 'Could not join community',
    'community.leaveError': 'Could not leave community',
    'community.joinSuccess': 'Successfully joined community',
    'community.leaveSuccess': 'Successfully left community',
    
    // Status Indicators
    'status.online': 'Online',
    'status.offline': 'Offline',
    'status.busy': 'Busy',
    'status.inactive': 'Inactive',
    
    // Bio/About
    'profile.defaultBio': 'Hello! Welcome to my profile.',
  'profile.birthday': 'Birthday',
  'profile.communities': 'Communities',
    
    // Messaging
    'messages.hub': 'Messages',
    'messages.direct': 'Messages',
    'messages.groups': 'Group Chats',
    'messages.newMessage': 'New Message',
    'messages.newConversation': 'New Conversation',
    'messages.newGroup': 'New Group',
    'messages.searchMessages': 'Search messages...',
    'messages.typeMessage': 'Type a message...',
    'messages.send': 'Send',
    'messages.loadingConversations': 'Loading conversations...',
    'messages.noConversations': 'No conversations yet',
    'messages.startConversation': 'Start a new conversation or create a group chat',
    'messages.noMessages': 'No messages yet',
    'messages.selectConversation': 'Select a conversation to start messaging',
    'messages.groupName': 'Group Name',
    'messages.groupNamePlaceholder': 'Enter group name...',
    'messages.selectMembers': 'Select Members',
    'messages.createGroup': 'Create Group',
    'messages.cancel': 'Cancel',
    'messages.search': 'Search...',
    'messages.selected': 'selected',
    'messages.loading': 'Loading...',
    'messages.searchFriends': 'Search friends...',
    'messages.noFriendsFound': 'No friends found matching your search',
    'messages.noFriendsYet': 'No friends yet. Add friends to start messaging!',
    'messages.searchToInvite': 'Search friends to invite...',
    'messages.noFriendsAvailable': 'No friends available',
    'messages.createNewGroup': 'Create New Group',
    'messages.groupName': 'Group Name',
    'messages.groupNamePlaceholder': 'Enter group name...',
    'messages.groupPhoto': 'Group Photo (Optional)',
    'messages.nextInviteFriends': 'Next: Invite Friends',
    'messages.membersSelected': 'members selected',
    'messages.memberSelected': 'member selected',
    'messages.creating': 'Creating...',
    'messages.newMessage': 'New Message',
    'messages.message': 'Message',
    'messages.findFriends': 'Find Friends',
    
    // Time ago
    'time.justNow': 'just now',
    'time.minuteAgo': 'minute ago',
    'time.minutesAgo': 'minutes ago',
    'time.hourAgo': 'hour ago',
    'time.hoursAgo': 'hours ago',
    'time.dayAgo': 'day ago',
    'time.daysAgo': 'days ago',
    'time.weekAgo': 'week ago',
    'time.weeksAgo': 'weeks ago',
    'time.monthAgo': 'month ago',
    'time.monthsAgo': 'months ago',
    'time.yearAgo': 'year ago',
    'time.yearsAgo': 'years ago',
    
    // About Page Tabs
    'about.tabs.about': 'About',
    'about.tabs.services': 'Services',
    'about.tabs.team': 'Team',
    
    // About Page Content
    'about.aboutUs': 'About Us',
    'about.description1': 'Welcome to our social network. Social Trial is a "living" digital ecosystem that combines real user interactions with "mock-bots" that bring your feed and messages to life 24 hours a day, 7 days a week.',
    'about.ourServices': 'Our Services',
    'about.service1': '🎨 Modern Frontend Development with React & Next.js',
    'about.service2': '📱 Fully Responsive Design for All Devices',
    'about.service3': '🎯 Intuitive User Interface & Experience Design',
    'about.service4': '🤖 AI Integration & Real-time Features',
    
    // User Profile Page
    'userProfile.memberSince': 'Member since',
    'userProfile.about': 'About',
    'userProfile.bio': 'Bio',
    'userProfile.location': 'Location',
    'userProfile.name': 'Name',
    'userProfile.avatar': 'Avatar URL',
    'userProfile.editProfile': 'Edit Profile',
    'userProfile.saveChanges': 'Save Changes',
    'userProfile.cancel': 'Cancel',
    'userProfile.activity': 'Activity',
    'userProfile.posts': 'Posts',
    'userProfile.favorites': 'Favorites',
    'userProfile.following': 'Following',
    'userProfile.followers': 'Followers',
    'userProfile.recentActivity': 'Recent Activity',
    'userProfile.recent': 'Recent',
    'userProfile.noRecentActivity': 'No recent activity to show.',
    'userProfile.noPosts': 'No posts yet. Share your first thought!',
    'userProfile.noFavorites': 'No favorites yet. Start exploring and save interesting content!',
    'userProfile.bioPlaceholder': 'Tell us about yourself...',
    'userProfile.locationPlaceholder': 'Where are you from?',
    'userProfile.namePlaceholder': 'Your name',
    
    // Feed Page
    'feed.createPostPlaceholder': 'What\'s on your mind?',
    'feed.postButton': 'Post',
    'feed.loadingPosts': 'Loading posts...',
    'feed.noPosts': 'No posts yet. Be the first to post something!',
    'feed.reportPost': 'Report Post',
    'feed.blockUser': 'Block User',
    'feed.hidePost': 'Hide Post',
    'feed.writeComment': 'Write a comment...',
    'feed.reply': 'Reply',
    'feed.globalChat': 'Global Chat (Users Only)',
    'feed.botChat': 'Talk with our Bots',
    'feed.typeMessage': 'Type a message...',
    'feed.askBots': 'Ask our bots...',
    'feed.send': 'Send',
    'feed.reportMessage': 'Report Message',
    'feed.loadingMessages': 'Loading messages...',
    'feed.noMessages': 'No messages yet. Start a conversation!',
    'feed.postTooLong': 'Post content must be 141 characters or less',
    'feed.postCreated': 'Post created successfully!',
    'feed.postFailed': 'Failed to create post. Please try again.',
    'feed.justNow': 'just now',
    'feed.minAgo': 'min ago',
    'feed.hourAgo': 'hour ago',
    'feed.hoursAgo': 'hours ago',
    'feed.dayAgo': 'day ago',
    'feed.daysAgo': 'days ago',
    
    // Home Page Auth
    'home.login': 'Login',
    'home.register': 'Register',
    'home.email': 'Email',
    'home.password': 'Password',
    'home.fullName': 'Full Name',
    'home.confirmPassword': 'Confirm Password',
    'home.forgotPassword': 'Forgot password?',
    'home.loggingIn': 'Logging in...',
    'home.registering': 'Registering...',
    'home.noAccount': 'Don\'t have an account?',
    'home.alreadyHaveAccount': 'Already have an account?',
    'home.helloWelcome': 'Hello, Welcome!',
    'home.welcomeBackTitle': 'Welcome Back!',
    'home.noAccountRegister': 'Don\'t have an account? Register or try our Demo',
    'home.demo': 'Demo',
    'home.orLoginWith': 'or login with other social platforms:',
    'home.orRegisterWith': 'or register with other social platforms:',
    'home.accountCreated': 'Account created successfully! Please login with your credentials.',
    'home.demoLoginFailed': 'Demo login failed. Please try again.',
    
    // Friends
    'friends.title': 'Friends',
    'friends.friendRequests': 'Friend Requests',
    'friends.allFriends': 'All Friends',
    'friends.accept': 'Accept',
    'friends.decline': 'Decline',
    'friends.remove': 'Remove Friend',
    'friends.noRequests': 'No pending friend requests',
    'friends.noFriends': 'No friends yet',
    'friends.searchFriends': 'Search friends...',
    'friends.showFriends': 'Show Friends',
    'friends.userFriends': '{name}\'s Friends',
    'friends.loading': 'Loading friends...',
    'friends.pending': 'Pending',
    'friends.accepted': 'Accepted',
    'friends.addFriend': 'Add Friend',
    'friends.unfriend': 'Unfriend',
    'friends.cancelRequest': 'Cancel Request',
    
    // Communities
    'communities.title': 'Communities',
    'communities.myCommu': 'My Communities',
    'communities.discover': 'Discover',
    'communities.create': 'Create Community',
    'communities.members': 'Members',
    'communities.posts': 'Posts',
    'communities.noCommunities': 'No communities yet',
    'communities.searchCommunities': 'Search communities...',
    'communities.allCategories': 'All Categories',
    'communities.loadingCommunities': 'Loading communities...',
    'communities.noCommunitiesFound': 'No communities found',
    'communities.tryDifferentSearch': 'Try a different search term.',
    'communities.join': 'Join',
    'communities.leave': 'Leave',
    'communities.noMembers': 'No members yet',
    'communities.memberBadge': 'Member',
    'communities.adminBadge': 'Admin',
    'communities.moderatorBadge': 'Moderator',
    'communities.creatorBadge': 'Creator',
    'communities.previous': 'Previous',
    'communities.next': 'Next',
    'communities.pageOf': 'Page {page} of {total}',
    'communities.loadingThreads': 'Loading threads...',
    'communities.loadingThread': 'Loading thread...',
    'communities.communityThreads': 'Community Threads',
    'communities.newThread': 'New Thread',
    'communities.noThreadsYet': 'No threads yet.',
    'communities.beFirstToDiscuss': 'Be the first to start a discussion!',
    'communities.createThread': 'Create New Thread',
    'communities.threadTitle': 'Thread Title',
    'communities.threadContent': 'Content',
    'communities.threadTitlePlaceholder': 'What do you want to discuss?',
    'communities.threadContentPlaceholder': 'Share your thoughts with the community...',
    'communities.titleRequired': 'Thread title is required',
    'communities.titleTooShort': 'Title must be at least 3 characters',
    'communities.titleTooLong': 'Title must be less than 100 characters',
    'communities.contentRequired': 'Thread content is required',
    'communities.contentTooShort': 'Content must be at least 10 characters',
    'communities.postThread': 'Post Thread',
    'communities.cancel': 'Cancel',
    'communities.reply': 'Reply',
    'communities.replies': 'Replies',
    'communities.writeReply': 'Write a reply...',
    'communities.postReply': 'Post Reply',
    'communities.failedToCreate': 'Failed to create community. Please try again.',
    'communities.subtitle': 'Build a space for people to connect and share',
    'communities.communityName': 'Community Name',
    'communities.nameRequired': '*',
    'communities.namePlaceholder': 'Enter community name',
    'communities.aboutCommunity': 'About this Community',
    'communities.descriptionPlaceholder': 'Describe what your community is about...',
    'communities.categorySelect': 'Select a category',
    'communities.privacySettings': 'Privacy Settings',
    'communities.privateInviteOnly': 'Private (Invite only)',
    'communities.publicAnyone': 'Public (Anyone can join)',
    'communities.membersApproved': 'Members must be approved before joining',
    'communities.anyoneCanJoin': 'Anyone can join this community',
    'communities.creating': 'Creating...',
    'communities.createCommunity': 'Create Community',
    'communities.failedToLoad': 'Failed to load community',
    'communities.failedToJoin': 'Failed to join community',
    'communities.failedToLeave': 'Failed to leave community',
    'communities.failedToCreateThread': 'Failed to create thread',
    'communities.threadNotFound': 'Thread not found',
    'communities.failedToLoadThread': 'Failed to load thread',
    'communities.failedToUpdateLike': 'Failed to update like',
    'communities.failedToAddComment': 'Failed to add comment',
    'communities.confirmDeleteComment': 'Delete this comment?',
    'communities.failedToDeleteComment': 'Failed to delete comment',
    'communities.confirmDeleteThread': 'Delete this thread? This action cannot be undone.',
    'communities.failedToDeleteThread': 'Failed to delete thread',
    'communities.noCommentsYet': 'No comments yet.',
    'communities.beFirstToComment': 'No comments yet. Be the first to comment!',
    'communities.addComment': 'Add your comment...',
    'communities.postComment': 'Post Comment',
    'communities.posting': 'Posting...',
    'communities.confirmLeave': 'Are you sure you want to leave this community?',
    'communities.categories': 'Categories',
    'communities.created': 'Created',
    'communities.about': 'About',
    'communities.threads': 'Threads',
    'communities.administrators': 'Administrators',
    'communities.by': 'by',
    // Community Categories
    'category.technology': 'Technology',
    'category.gaming': 'Gaming',
    'category.music': 'Music',
    'category.sports': 'Sports',
    'category.education': 'Education',
    'category.entertainment': 'Entertainment',
    'category.lifestyle': 'Lifestyle',
    'category.business': 'Business',
    'category.health': 'Health',
    'category.travel': 'Travel',
    'category.food': 'Food',
    'category.art': 'Art',
    'category.other': 'Other',
    
    // Marketplace
    'marketplace.title': 'Marketplace',
    'marketplace.newProduct': 'New Product',
    'marketplace.searchProducts': 'Search products, categories, sellers...',
    'marketplace.search': 'Search',
    'marketplace.clearSearch': 'Clear Search',
    'marketplace.category': 'Category',
    'marketplace.price': 'Price',
    'marketplace.condition': 'Condition',
    'marketplace.location': 'Location',
    'marketplace.description': 'Description',
    'marketplace.contactSeller': 'Contact Seller',
    'marketplace.contact': 'Contact',
    'marketplace.noProducts': 'No products available',
    'marketplace.noProductsFound': 'No products found',
    'marketplace.tryAdjusting': 'Try adjusting your search or browse all products',
    'marketplace.new': 'New',
    'marketplace.used': 'Used',
    'marketplace.likeNew': 'Like New',
    'marketplace.good': 'Good',
    'marketplace.acceptable': 'Acceptable',
    'marketplace.outOfStock': 'Out of Stock',
    'marketplace.lowStock': 'Only',
    'marketplace.left': 'left',
    'marketplace.listProduct': 'List a Product',
    'marketplace.listNewProduct': 'List New Product',
    'marketplace.productName': 'Product Name',
    'marketplace.productDescription': 'Product Description',
    'marketplace.productPrice': 'Price',
    'marketplace.productCondition': 'Condition',
    'marketplace.productCategory': 'Category',
    'marketplace.productLocation': 'Location',
    'marketplace.uploadImages': 'Upload Images',
    'marketplace.productImages': 'Product Images',
    'marketplace.addImageUrl': 'Add Image URL',
    'marketplace.imageUrl': 'Image URL',
    'marketplace.invalidUrl': 'Invalid URL',
    'marketplace.primary': 'Primary',
    'marketplace.submit': 'List Product',
    'marketplace.cancel': 'Cancel',
    'marketplace.loading': 'Loading products...',
    'marketplace.loadingProduct': 'Loading...',
    'marketplace.seller': 'Seller',
    'marketplace.soldBy': 'Sold by',
    'marketplace.details': 'Details',
    'marketplace.noImage': 'No Image',
    'marketplace.addToFavorites': 'Add to favorites',
    'marketplace.removeFromFavorites': 'Remove from favorites',
    'marketplace.reviews': 'reviews',
    'marketplace.review': 'review',
    'marketplace.found': 'Found',
    'marketplace.product': 'product',
    'marketplace.products': 'products',
    'marketplace.for': 'for',
    'marketplace.showing': 'Showing',
    'marketplace.loadMore': 'Load More Products',
    'marketplace.tryAgain': 'Try Again',
    'marketplace.failedToLoad': 'Failed to load products',
    'marketplace.quantity': 'Quantity',
    'marketplace.available': 'available',
    'marketplace.addToCart': 'Add to Cart',
    'marketplace.adding': 'Adding...',
    'marketplace.addedToCart': 'Added to cart successfully!',
    'marketplace.buyNow': 'Buy Now',
    'marketplace.stockQuantity': 'Stock Quantity',
    'marketplace.required': '*',
    'marketplace.optional': '(Optional)',
    'marketplace.enterProductName': 'Enter product name',
    'marketplace.describeProduct': 'Describe your product in detail...',
    'marketplace.shareItems': 'Share your items with the community',
    'marketplace.addUpTo5': 'Add up to 5 image URLs for your product',
    'marketplace.selectCategories': 'Select categories that best describe your product',
    'marketplace.selected': 'selected',
    'marketplace.categories': 'Categories',
    'marketplace.listing': 'Listing...',
    'marketplace.outOfStockNotice': 'This item is currently out of stock',
    'marketplace.messagingComingSoon': 'Messaging feature coming soon!',
    
    // Gallery
    'gallery.title': 'Gallery',
    'gallery.uploadPhoto': 'Upload Photo',
    'gallery.noPhotos': 'No photos yet',
    'gallery.delete': 'Delete',
    'gallery.addPhoto': 'Add Photo',
    'gallery.loadingPhotos': 'Loading photos...',
    'gallery.uploadFirst': 'Upload your first photo to get started!',
    'gallery.uploadedOn': 'Uploaded on',
    'gallery.addNewPhoto': 'Add New Photo',
    'gallery.selectPhoto': 'Click to select a photo or drag and drop',
    'gallery.fileTypes': 'PNG, JPG, GIF up to 10MB',
    'gallery.changePhoto': 'Change Photo',
    'gallery.caption': 'Caption (optional)',
    'gallery.captionPlaceholder': 'Add a caption for your photo...',
    'gallery.cancel': 'Cancel',
    'gallery.uploading': 'Uploading...',
    'gallery.uploadSuccess': 'Photo "{caption}" uploaded successfully!',
    'gallery.uploadFailed': 'Failed to upload photo. Please try again.',
    'gallery.selectPhotoAlert': 'Please select a photo to upload',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.noNotifications': 'No notifications yet',
    'notifications.viewAll': 'View all notifications',
    'notifications.justNow': 'just now',
    'notifications.minutesAgo': '{count}m ago',
    'notifications.hoursAgo': '{count}h ago',
    'notifications.daysAgo': '{count}d ago',
    
    // DevCard
    'devCard.role': 'Full-Stack Dev',
    'devCard.github': 'GitHub',
    'devCard.portfolio': 'Portfolio',
    'devCard.profile': 'Profile',
    'devCard.description': 'Developer behind this social network project, responsible for all architecture, implementation and deployment of the application. The project was built with a focus on scalability, performance and user experience, integrating modern technologies in both frontend and backend.'
  },
  
  pt: {
    // Navbar
    'nav.home': 'Início',
    'nav.about': 'Sobre Nós',
    'nav.profile': 'Perfil',
    'nav.feed': 'Feed',
  'nav.communities': 'Comunidades',
  'nav.marketplace' : 'Mercado',
    'nav.login': 'Entrar',
    'nav.register': 'Cadastrar',
    'nav.logo': 'Logo',
    
    // Sidebar
    'sidebar.title': 'Configurações e Mais',
    'sidebar.user': 'Conta do Usuário',
    'sidebar.welcome': 'Bem-vindo',
    'sidebar.logout': 'Sair',
    'sidebar.loginToAccount': 'Faça login em sua conta',
    'sidebar.theme': 'Tema',
  'sidebar.darkMode': 'Modo Escuro',
  'sidebar.lightMode': 'Modo Claro',
    'sidebar.navigation': 'Navegação',
    'sidebar.configurations': 'Configurações',
    'sidebar.language': 'Idioma',
    
    // Home Page
    'home.welcome': 'Bem-vindo ao Nosso App',
    'home.welcomeBack': 'Bem-vindo de volta',
    'home.getStarted': 'Começar',
    'home.getStartedText': 'Pronto para se juntar a nós? Crie uma conta ou faça login em sua conta existente.',
    'home.signUp': 'Cadastrar-se',
    'home.loginBtn': 'Entrar',
    'home.yourFeed': 'Seu Feed Pessoal',
    'home.feedDescription': 'Mantenha-se atualizado com conteúdo personalizado apenas para você.',
    'home.welcomeMessage': 'Ótimo te ver novamente! Sua experiência personalizada te aguarda.',
    'home.feedComingSoon': 'O conteúdo do feed está sendo preparado. Volte em breve para atualizações!',
    'home.quickActions': 'Ações Rápidas',
    'home.footer': '© 2025 Nosso App. Todos os direitos reservados.',
    
    // About/Features (moved from landing)
    'landing.about': 'Sobre Nós',
    'landing.aboutText': 'Esta é uma página inicial simples construída com React. Fornecemos serviços e soluções incríveis para nossos usuários.',
    'landing.features': 'Recursos',
    'landing.feature1': 'Interface fácil de usar',
    'landing.feature2': 'Autenticação segura',
    'landing.feature3': 'Rápido e confiável',
    'landing.feature4': 'Suporte 24/7',
    
    // Feed Page
    'feed.title': 'Feed',
    'feed.description': 'Mantenha-se atualizado com as últimas postagens e atividades da nossa comunidade.',
    'feed.comingSoon': 'Conteúdo do feed em breve! Aqui serão exibidas postagens, atualizações e atividades da comunidade.',
    
    // About Page
    'about.title': 'Sobre Nossa Empresa',
    'about.description': 'Saiba mais sobre nossa missão, valores e a equipe por trás de nossas soluções inovadoras.',
    'about.mission': 'Nossa Missão',
    'about.missionText': 'Somos dedicados a fornecer soluções tecnológicas de ponta que capacitam empresas e indivíduos a alcançar seus objetivos. Nosso compromisso com a excelência orienta tudo o que fazemos.',
    'about.team': 'Nossa Equipe',
    'about.teamText': 'Nossa equipe diversificada de especialistas reúne anos de experiência em tecnologia, design e atendimento ao cliente. Trabalhamos colaborativamente para oferecer a melhor experiência possível aos nossos usuários.',
    
    // Login Page
    'login.title': 'Entrar',
    'login.email': 'Email:',
    'login.password': 'Senha:',
    'login.loginBtn': 'Entrar',
    'login.noAccount': 'Não tem uma conta?',
    'login.registerHere': 'Cadastre-se aqui',
    
    // Register Page
    'register.title': 'Cadastrar',
    'register.firstName': 'Nome:',
    'register.lastName': 'Sobrenome:',
    'register.email': 'Email:',
    'register.password': 'Senha:',
    'register.confirmPassword': 'Confirmar Senha:',
    'register.registerBtn': 'Cadastrar',
    'register.hasAccount': 'Já tem uma conta?',
    'register.loginHere': 'Faça login aqui',
    
    // Form validation messages
    'validation.fillAllFields': 'Por favor, preencha todos os campos',
    'validation.passwordsMismatch': 'As senhas não coincidem',
    'validation.passwordTooShort': 'A senha deve ter pelo menos 6 caracteres',
    'validation.loginDemo': 'A funcionalidade de login seria implementada aqui',
    'validation.registerDemo': 'A funcionalidade de cadastro seria implementada aqui',
    
    // Profile Page
    'profile.aboutMe': 'Sobre Mim',
    'profile.details' : 'Detalhes',
    'profile.interests': 'Interesses',
    'profile.contact': 'Contato',
    'profile.leaveMessage': 'Deixar uma mensagem',
    'profile.age': 'Idade',
    'profile.status': 'Status',
    'profile.location': 'Localização',
    'profile.occupation': 'Profissão',
    'profile.memberSince': 'Membro desde',
    'profile.single': 'Solteiro(a)',
    'profile.webDeveloper': 'Desenvolvedor Web',
  // Relationship statuses (use keys as stable identifiers)
  'relationship.single': 'Solteiro(a)',
  'relationship.situationship': 'Relacionamento indefinido',
  'relationship.inRelationship': 'Em um relacionamento',
  'relationship.engaged': 'Noivado(a)',
  'relationship.married': 'Casado(a)',
  'relationship.divorced': 'Divorciado(a)',
  'relationship.separated': 'Separado(a)',
  'relationship.widowed': 'Viúvo(a)',
    
    // Profile Tabs
    'profile.kudos': 'Elogios',
    'profile.photos': 'Fotos',
    'profile.friends': 'Amigos',
    'profile.showMore': 'Mostrar Mais',
    'profile.viewAll': 'Ver Todos',
  'profile.createNew': 'Criar Comunidade',
    'profile.totalPhotos': 'fotos no total',
  'profile.totalFriends': 'amigos',
    'profile.totalMembers': 'membros',
  'profile.contact': 'Contato',
  'profile.leaveMessage': 'Deixar uma mensagem',
  'profile.message': 'Mensagem',
  'profile.opening': 'Abrindo...',
  'profile.unfriend': 'Desfazer Amizade',
  'profile.removing': 'Removendo...',
  'profile.addFriend': 'Adicionar Amigo',
  'profile.sending': 'Enviando...',
  'profile.edit': 'Editar',  // Gallery
  'gallery.backToProfile': '← Voltar ao perfil de {name}',
  'gallery.photosTitle': 'Fotos de {name}',
  'gallery.photosCount': '{count} fotos',
    
    // Community Model (public, member-only posting, join requests)
    'community.publicViewable': 'Qualquer pessoa pode ver esta comunidade',
    'community.membersPost': 'Apenas membros podem postar',
    'community.requestJoin': 'Solicitar participação',
    'community.joinSent': 'Solicitação enviada',
    'community.waitingApproval': 'Aguardando aprovação',
    'community.youAreMember': 'Você é membro',
    'community.postThread': 'Criar tópico',
    'community.join': 'Participar',
    'community.leave': 'Sair',
    'community.joined': 'Participando',
    'community.notMember': 'Você não é membro',
    'community.membersOnly': 'Somente membros',
    'community.approvalRequired': 'Aprovação necessária para participar',
    'community.joinError': 'Não foi possível participar da comunidade',
    'community.leaveError': 'Não foi possível sair da comunidade',
    'community.joinSuccess': 'Participação confirmada',
    'community.leaveSuccess': 'Saída confirmada',
    
    // Status Indicators
    'status.online': 'Online',
    'status.offline': 'Offline',
    'status.busy': 'Ocupado',
    'status.inactive': 'Inativo',
    
    // Bio/About
    'profile.defaultBio': 'Olá! Bem-vindo ao meu perfil.',
  'profile.birthday': 'Aniversário',
  'profile.communities': 'Comunidades',
    
    // Messaging
    'messages.hub': 'Mensagens',
    'messages.direct': 'Mensagens',
    'messages.groups': 'Chats em Grupo',
    'messages.newMessage': 'Nova Mensagem',
    'messages.newConversation': 'Nova conversa',
    'messages.newGroup': 'Novo grupo',
    'messages.searchMessages': 'Buscar mensagens...',
    'messages.typeMessage': 'Digite uma mensagem...',
    'messages.send': 'Enviar',
    'messages.loadingConversations': 'Carregando conversas...',
    'messages.noConversations': 'Nenhuma conversa ainda',
    'messages.startConversation': 'Inicie uma nova conversa ou crie um chat em grupo',
    'messages.noMessages': 'Nenhuma mensagem ainda',
    'messages.selectConversation': 'Selecione uma conversa para começar a enviar mensagens',
    'messages.groupName': 'Nome do Grupo',
    'messages.groupNamePlaceholder': 'Digite o nome do grupo...',
    'messages.selectMembers': 'Selecionar Membros',
    'messages.createGroup': 'Criar Grupo',
    'messages.cancel': 'Cancelar',
    'messages.search': 'Pesquisar...',
    'messages.selected': 'selecionado(s)',
    'messages.loading': 'Carregando...',
    'messages.searchFriends': 'Pesquisar amigos...',
    'messages.noFriendsFound': 'Nenhum amigo encontrado correspondente à sua pesquisa',
    'messages.noFriendsYet': 'Nenhum amigo ainda. Adicione amigos para começar a enviar mensagens!',
    'messages.searchToInvite': 'Pesquisar amigos para convidar...',
    'messages.noFriendsAvailable': 'Nenhum amigo disponível',
    'messages.createNewGroup': 'Criar Novo Grupo',
    'messages.groupName': 'Nome do Grupo',
    'messages.groupNamePlaceholder': 'Digite o nome do grupo...',
    'messages.groupPhoto': 'Foto do Grupo (Opcional)',
    'messages.nextInviteFriends': 'Próximo: Convidar Amigos',
    'messages.membersSelected': 'membros selecionados',
    'messages.memberSelected': 'membro selecionado',
    'messages.creating': 'Criando...',
    'messages.newMessage': 'Nova Mensagem',
    'messages.message': 'Mensagem',
    'messages.findFriends': 'Encontrar Amigos',
    
    // Time ago
    'time.justNow': 'agora mesmo',
    'time.minuteAgo': 'minuto atrás',
    'time.minutesAgo': 'minutos atrás',
    'time.hourAgo': 'hora atrás',
    'time.hoursAgo': 'horas atrás',
    'time.dayAgo': 'dia atrás',
    'time.daysAgo': 'dias atrás',
    'time.weekAgo': 'semana atrás',
    'time.weeksAgo': 'semanas atrás',
    'time.monthAgo': 'mês atrás',
    'time.monthsAgo': 'meses atrás',
    'time.yearAgo': 'ano atrás',
    'time.yearsAgo': 'anos atrás',
    
    // About Page Tabs
    'about.tabs.about': 'Sobre',
    'about.tabs.services': 'Serviços',
    'about.tabs.team': 'Equipe',
    
    // About Page Content
    'about.aboutUs': 'Sobre Nós',
    'about.description1': 'Bem-vindo à nossa rede social. A Social Trial um ecossistema digital "vivo" que combina interações reais de usuários com "mock-bots" que dão vida ao seu feed e suas mensagens 24 horas por dia, 7 dias por semana.',
    'about.ourServices': 'Nossos Serviços',
    'about.service1': '🎨 Desenvolvimento Frontend Moderno com React & Next.js',
    'about.service2': '📱 Design Totalmente Responsivo para Todos os Dispositivos',
    'about.service3': '🎯 Design Intuitivo de Interface e Experiência do Usuário',
    'about.service4': '🤖 Integração de IA & Recursos em Tempo Real',
    
    // User Profile Page
    'userProfile.memberSince': 'Membro desde',
    'userProfile.about': 'Sobre',
    'userProfile.bio': 'Bio',
    'userProfile.location': 'Localização',
    'userProfile.name': 'Nome',
    'userProfile.avatar': 'URL do Avatar',
    'userProfile.editProfile': 'Editar Perfil',
    'userProfile.saveChanges': 'Salvar Alterações',
    'userProfile.cancel': 'Cancelar',
    'userProfile.activity': 'Atividade',
    'userProfile.posts': 'Postagens',
    'userProfile.favorites': 'Favoritos',
    'userProfile.following': 'Seguindo',
    'userProfile.followers': 'Seguidores',
    'userProfile.recentActivity': 'Atividade Recente',
    'userProfile.recent': 'Recente',
    'userProfile.noRecentActivity': 'Nenhuma atividade recente para mostrar.',
    'userProfile.noPosts': 'Nenhuma postagem ainda. Compartilhe seu primeiro pensamento!',
    'userProfile.noFavorites': 'Nenhum favorito ainda. Comece a explorar e salve conteúdo interessante!',
    'userProfile.bioPlaceholder': 'Conte-nos sobre você...',
    'userProfile.locationPlaceholder': 'De onde você é?',
    'userProfile.namePlaceholder': 'Seu nome',
    
    // Feed Page
    'feed.createPostPlaceholder': 'No que você está pensando?',
    'feed.postButton': 'Publicar',
    'feed.loadingPosts': 'Carregando postagens...',
    'feed.noPosts': 'Nenhuma postagem ainda. Seja o primeiro a postar algo!',
    'feed.reportPost': 'Denunciar Postagem',
    'feed.blockUser': 'Bloquear Usuário',
    'feed.hidePost': 'Ocultar Postagem',
    'feed.writeComment': 'Escreva um comentário...',
    'feed.reply': 'Responder',
    'feed.globalChat': 'Chat Global (Somente Usuários)',
    'feed.botChat': 'Converse com nossos Bots',
    'feed.typeMessage': 'Digite uma mensagem...',
    'feed.askBots': 'Pergunte aos nossos bots...',
    'feed.send': 'Enviar',
    'feed.reportMessage': 'Denunciar Mensagem',
    'feed.loadingMessages': 'Carregando mensagens...',
    'feed.noMessages': 'Ainda não há mensagens. Inicie uma conversa!',
    'feed.postTooLong': 'O conteúdo da postagem deve ter 141 caracteres ou menos',
    'feed.postCreated': 'Postagem criada com sucesso!',
    'feed.postFailed': 'Falha ao criar postagem. Por favor, tente novamente.',
    'feed.justNow': 'agora mesmo',
    'feed.minAgo': 'min atrás',
    'feed.hourAgo': 'hora atrás',
    'feed.hoursAgo': 'horas atrás',
    'feed.dayAgo': 'dia atrás',
    'feed.daysAgo': 'dias atrás',
    
    // Home Page Auth
    'home.login': 'Entrar',
    'home.register': 'Cadastrar',
    'home.email': 'Email',
    'home.password': 'Senha',
    'home.fullName': 'Nome Completo',
    'home.confirmPassword': 'Confirmar Senha',
    'home.forgotPassword': 'Esqueceu a senha?',
    'home.loggingIn': 'Entrando...',
    'home.registering': 'Cadastrando...',
    'home.noAccount': 'Não tem uma conta?',
    'home.alreadyHaveAccount': 'Já tem uma conta?',
    'home.helloWelcome': 'Olá, Bem-vindo!',
    'home.welcomeBackTitle': 'Bem-vindo de Volta!',
    'home.noAccountRegister': 'Não tem uma conta? Cadastre-se ou experimente nossa Demo',
    'home.demo': 'Demo',
    'home.orLoginWith': 'ou faça login com outras plataformas sociais:',
    'home.orRegisterWith': 'ou cadastre-se com outras plataformas sociais:',
    'home.accountCreated': 'Conta criada com sucesso! Por favor, faça login com suas credenciais.',
    'home.demoLoginFailed': 'Falha no login demo. Por favor, tente novamente.',
    
    // Friends
    'friends.title': 'Amigos',
    'friends.friendRequests': 'Solicitações de Amizade',
    'friends.allFriends': 'Todos os Amigos',
    'friends.accept': 'Aceitar',
    'friends.decline': 'Recusar',
    'friends.remove': 'Remover Amigo',
    'friends.noRequests': 'Nenhuma solicitação de amizade pendente',
    'friends.noFriends': 'Nenhum amigo ainda',
    'friends.searchFriends': 'Pesquisar amigos...',
    'friends.showFriends': 'Mostrar Amigos',
    'friends.userFriends': 'Amigos de {name}',
    'friends.loading': 'Carregando amigos...',
    'friends.pending': 'Pendente',
    'friends.accepted': 'Aceito',
    'friends.addFriend': 'Adicionar Amigo',
    'friends.unfriend': 'Desfazer Amizade',
    'friends.cancelRequest': 'Cancelar Solicitação',
    
    // Communities
    'communities.title': 'Comunidades',
    'communities.myCommu': 'Minhas Comunidades',
    'communities.discover': 'Descobrir',
    'communities.create': 'Criar Comunidade',
    'communities.members': 'Membros',
    'communities.posts': 'Postagens',
    'communities.noCommunities': 'Nenhuma comunidade ainda',
    'communities.searchCommunities': 'Pesquisar comunidades...',
    'communities.allCategories': 'Todas as Categorias',
    'communities.loadingCommunities': 'Carregando comunidades...',
    'communities.noCommunitiesFound': 'Nenhuma comunidade encontrada',
    'communities.tryDifferentSearch': 'Tente um termo de pesquisa diferente.',
    'communities.join': 'Participar',
    'communities.leave': 'Sair',
    'communities.noMembers': 'Ainda não há membros',
    'communities.memberBadge': 'Membro',
    'communities.adminBadge': 'Admin',
    'communities.moderatorBadge': 'Moderador',
    'communities.creatorBadge': 'Criador',
    'communities.previous': 'Anterior',
    'communities.next': 'Próximo',
    'communities.pageOf': 'Página {page} de {total}',
    'communities.loadingThreads': 'Carregando tópicos...',
    'communities.loadingThread': 'Carregando tópico...',
    'communities.communityThreads': 'Tópicos da Comunidade',
    'communities.newThread': 'Novo Tópico',
    'communities.noThreadsYet': 'Ainda não há tópicos.',
    'communities.beFirstToDiscuss': 'Seja o primeiro a iniciar uma discussão!',
    'communities.createThread': 'Criar Novo Tópico',
    'communities.threadTitle': 'Título do Tópico',
    'communities.threadContent': 'Conteúdo',
    'communities.threadTitlePlaceholder': 'O que você quer discutir?',
    'communities.threadContentPlaceholder': 'Compartilhe seus pensamentos com a comunidade...',
    'communities.titleRequired': 'O título do tópico é obrigatório',
    'communities.titleTooShort': 'O título deve ter pelo menos 3 caracteres',
    'communities.titleTooLong': 'O título deve ter menos de 100 caracteres',
    'communities.contentRequired': 'O conteúdo do tópico é obrigatório',
    'communities.contentTooShort': 'O conteúdo deve ter pelo menos 10 caracteres',
    'communities.postThread': 'Publicar Tópico',
    'communities.cancel': 'Cancelar',
    'communities.reply': 'Responder',
    'communities.replies': 'Respostas',
    'communities.writeReply': 'Escreva uma resposta...',
    'communities.postReply': 'Publicar Resposta',
    'communities.failedToCreate': 'Falha ao criar comunidade. Por favor, tente novamente.',
    'communities.subtitle': 'Construa um espaço para pessoas se conectarem e compartilharem',
    'communities.communityName': 'Nome da Comunidade',
    'communities.nameRequired': '*',
    'communities.namePlaceholder': 'Digite o nome da comunidade',
    'communities.aboutCommunity': 'Sobre esta Comunidade',
    'communities.descriptionPlaceholder': 'Descreva sobre o que é sua comunidade...',
    'communities.categorySelect': 'Selecione uma categoria',
    'communities.privacySettings': 'Configurações de Privacidade',
    'communities.privateInviteOnly': 'Privada (Somente por convite)',
    'communities.publicAnyone': 'Pública (Qualquer um pode participar)',
    'communities.membersApproved': 'Membros devem ser aprovados antes de participar',
    'communities.anyoneCanJoin': 'Qualquer um pode participar desta comunidade',
    'communities.creating': 'Criando...',
    'communities.createCommunity': 'Criar Comunidade',
    'communities.failedToLoad': 'Falha ao carregar comunidade',
    'communities.failedToJoin': 'Falha ao entrar na comunidade',
    'communities.failedToLeave': 'Falha ao sair da comunidade',
    'communities.failedToCreateThread': 'Falha ao criar tópico',
    'communities.threadNotFound': 'Tópico não encontrado',
    'communities.failedToLoadThread': 'Falha ao carregar tópico',
    'communities.failedToUpdateLike': 'Falha ao atualizar curtida',
    'communities.failedToAddComment': 'Falha ao adicionar comentário',
    'communities.confirmDeleteComment': 'Excluir este comentário?',
    'communities.failedToDeleteComment': 'Falha ao excluir comentário',
    'communities.confirmDeleteThread': 'Excluir este tópico? Esta ação não pode ser desfeita.',
    'communities.failedToDeleteThread': 'Falha ao excluir tópico',
    'communities.noCommentsYet': 'Ainda não há comentários.',
    'communities.beFirstToComment': 'Ainda não há comentários. Seja o primeiro a comentar!',
    'communities.addComment': 'Adicione seu comentário...',
    'communities.postComment': 'Publicar Comentário',
    'communities.posting': 'Publicando...',
    'communities.confirmLeave': 'Tem certeza de que deseja sair desta comunidade?',
    'communities.categories': 'Categorias',
    'communities.created': 'Criado',
    'communities.about': 'Sobre',
    'communities.threads': 'Tópicos',
    'communities.administrators': 'Administradores',
    'communities.by': 'por',
    // Community Categories
    'category.technology': 'Tecnologia',
    'category.gaming': 'Jogos',
    'category.music': 'Música',
    'category.sports': 'Esportes',
    'category.education': 'Educação',
    'category.entertainment': 'Entretenimento',
    'category.lifestyle': 'Estilo de Vida',
    'category.business': 'Negócios',
    'category.health': 'Saúde',
    'category.travel': 'Viagens',
    'category.food': 'Comida',
    'category.art': 'Arte',
    'category.other': 'Outros',
    
    // Marketplace
    'marketplace.title': 'Mercado',
    'marketplace.newProduct': 'Novo Produto',
    'marketplace.searchProducts': 'Pesquisar produtos, categorias, vendedores...',
    'marketplace.search': 'Pesquisar',
    'marketplace.clearSearch': 'Limpar Pesquisa',
    'marketplace.category': 'Categoria',
    'marketplace.price': 'Preço',
    'marketplace.condition': 'Condição',
    'marketplace.location': 'Localização',
    'marketplace.description': 'Descrição',
    'marketplace.contactSeller': 'Contatar Vendedor',
    'marketplace.contact': 'Contatar',
    'marketplace.noProducts': 'Nenhum produto disponível',
    'marketplace.noProductsFound': 'Nenhum produto encontrado',
    'marketplace.tryAdjusting': 'Tente ajustar sua pesquisa ou navegar por todos os produtos',
    'marketplace.new': 'Novo',
    'marketplace.used': 'Usado',
    'marketplace.likeNew': 'Como Novo',
    'marketplace.good': 'Bom',
    'marketplace.acceptable': 'Aceitável',
    'marketplace.outOfStock': 'Fora de Estoque',
    'marketplace.lowStock': 'Apenas',
    'marketplace.left': 'restante',
    'marketplace.listProduct': 'Anunciar um Produto',
    'marketplace.listNewProduct': 'Anunciar Novo Produto',
    'marketplace.productName': 'Nome do Produto',
    'marketplace.productDescription': 'Descrição do Produto',
    'marketplace.productPrice': 'Preço',
    'marketplace.productCondition': 'Condição',
    'marketplace.productCategory': 'Categoria',
    'marketplace.productLocation': 'Localização',
    'marketplace.uploadImages': 'Enviar Imagens',
    'marketplace.productImages': 'Imagens do Produto',
    'marketplace.addImageUrl': 'Adicionar URL da Imagem',
    'marketplace.imageUrl': 'URL da Imagem',
    'marketplace.invalidUrl': 'URL Inválida',
    'marketplace.primary': 'Principal',
    'marketplace.submit': 'Anunciar Produto',
    'marketplace.cancel': 'Cancelar',
    'marketplace.loading': 'Carregando produtos...',
    'marketplace.loadingProduct': 'Carregando...',
    'marketplace.seller': 'Vendedor',
    'marketplace.soldBy': 'Vendido por',
    'marketplace.details': 'Detalhes',
    'marketplace.noImage': 'Sem Imagem',
    'marketplace.addToFavorites': 'Adicionar aos favoritos',
    'marketplace.removeFromFavorites': 'Remover dos favoritos',
    'marketplace.reviews': 'avaliações',
    'marketplace.review': 'avaliação',
    'marketplace.found': 'Encontrado',
    'marketplace.product': 'produto',
    'marketplace.products': 'produtos',
    'marketplace.for': 'para',
    'marketplace.showing': 'Mostrando',
    'marketplace.loadMore': 'Carregar Mais Produtos',
    'marketplace.tryAgain': 'Tentar Novamente',
    'marketplace.failedToLoad': 'Falha ao carregar produtos',
    'marketplace.quantity': 'Quantidade',
    'marketplace.available': 'disponível',
    'marketplace.addToCart': 'Adicionar ao Carrinho',
    'marketplace.adding': 'Adicionando...',
    'marketplace.addedToCart': 'Adicionado ao carrinho com sucesso!',
    'marketplace.buyNow': 'Comprar Agora',
    'marketplace.stockQuantity': 'Quantidade em Estoque',
    'marketplace.required': '*',
    'marketplace.optional': '(Opcional)',
    'marketplace.enterProductName': 'Digite o nome do produto',
    'marketplace.describeProduct': 'Descreva seu produto em detalhes...',
    'marketplace.shareItems': 'Compartilhe seus itens com a comunidade',
    'marketplace.addUpTo5': 'Adicione até 5 URLs de imagens para seu produto',
    'marketplace.selectCategories': 'Selecione categorias que melhor descrevem seu produto',
    'marketplace.selected': 'selecionado',
    'marketplace.categories': 'Categorias',
    'marketplace.listing': 'Anunciando...',
    'marketplace.outOfStockNotice': 'Este item está atualmente fora de estoque',
    'marketplace.messagingComingSoon': 'Recurso de mensagens em breve!',
    
    // Gallery
    'gallery.title': 'Galeria',
    'gallery.uploadPhoto': 'Enviar Foto',
    'gallery.noPhotos': 'Nenhuma foto ainda',
    'gallery.delete': 'Excluir',
    'gallery.addPhoto': 'Adicionar Foto',
    'gallery.loadingPhotos': 'Carregando fotos...',
    'gallery.uploadFirst': 'Envie sua primeira foto para começar!',
    'gallery.uploadedOn': 'Enviado em',
    'gallery.addNewPhoto': 'Adicionar Nova Foto',
    'gallery.selectPhoto': 'Clique para selecionar uma foto ou arraste e solte',
    'gallery.fileTypes': 'PNG, JPG, GIF até 10MB',
    'gallery.changePhoto': 'Mudar Foto',
    'gallery.caption': 'Legenda (opcional)',
    'gallery.captionPlaceholder': 'Adicione uma legenda para sua foto...',
    'gallery.cancel': 'Cancelar',
    'gallery.uploading': 'Enviando...',
    'gallery.uploadSuccess': 'Foto "{caption}" enviada com sucesso!',
    'gallery.uploadFailed': 'Falha ao enviar foto. Por favor, tente novamente.',
    'gallery.selectPhotoAlert': 'Por favor, selecione uma foto para enviar',
    
    // Notifications
    'notifications.title': 'Notificações',
    'notifications.markAllRead': 'Marcar todas como lidas',
    'notifications.noNotifications': 'Nenhuma notificação ainda',
    'notifications.viewAll': 'Ver todas as notificações',
    'notifications.justNow': 'agora mesmo',
    'notifications.minutesAgo': '{count}m atrás',
    'notifications.hoursAgo': '{count}h atrás',
    'notifications.daysAgo': '{count}d atrás',
    
    // DevCard
    'devCard.role': 'Dev Full-Stack',
    'devCard.github': 'GitHub',
    'devCard.portfolio': 'Portfólio',
    'devCard.profile': 'Perfil',
    'devCard.description': 'Desenvolvedor por trás deste projeto de rede social, responsável por toda a arquitetura, implementação e deploy da aplicação. O projeto foi construído com foco em escalabilidade, performance e experiência do usuário, integrando tecnologias modernas tanto no frontend quanto no backend.'
  },
  
  es: {
    // Navbar
    'nav.home': 'Inicio',
    'nav.about': 'Sobre Nosotros',
    'nav.profile': 'Perfil',
    'nav.feed': 'Feed',
    'nav.communities': 'Comunidades',
    'nav.marketplace' : 'Mercado',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.logo': 'Logo',
    
    // Sidebar
    'sidebar.title': 'Configuraciones y Más',
    'sidebar.user': 'Cuenta de Usuario',
    'sidebar.welcome': 'Bienvenido',
    'sidebar.logout': 'Cerrar Sesión',
    'sidebar.loginToAccount': 'Inicia sesión en tu cuenta',
    'sidebar.theme': 'Tema',
  'sidebar.darkMode': 'Modo Oscuro',
  'sidebar.lightMode': 'Modo Claro',
    'sidebar.navigation': 'Navegación',
    'sidebar.configurations': 'Configuraciones',
    'sidebar.language': 'Idioma',
    
    // Home Page
    'home.welcome': 'Bienvenido a Nuestra App',
    'home.welcomeBack': 'Bienvenido de vuelta',
    'home.getStarted': 'Empezar',
    'home.getStartedText': '¿Listo para unirte a nosotros? Crea una cuenta o inicia sesión en tu cuenta existente.',
    'home.signUp': 'Registrarse',
    'home.loginBtn': 'Iniciar Sesión',
    'home.yourFeed': 'Tu Feed Personal',
    'home.feedDescription': 'Mantente actualizado con contenido personalizado solo para ti.',
    'home.welcomeMessage': '¡Qué bueno verte de nuevo! Tu experiencia personalizada te espera.',
    'home.feedComingSoon': 'El contenido del feed se está preparando. ¡Vuelve pronto para actualizaciones!',
    'home.quickActions': 'Acciones Rápidas',
    'home.footer': '© 2025 Nuestra App. Todos los derechos reservados.',
    
    // About/Features (moved from landing)
    'landing.about': 'Acerca de Nosotros',
    'landing.aboutText': 'Esta es una página de inicio simple construida con React. Proporcionamos servicios y soluciones increíbles para nuestros usuarios.',
    'landing.features': 'Características',
    'landing.feature1': 'Interfaz fácil de usar',
    'landing.feature2': 'Autenticación segura',
    'landing.feature3': 'Rápido y confiable',
    'landing.feature4': 'Soporte 24/7',
    
    // Feed Page
    'feed.title': 'Feed',
    'feed.description': 'Mantente actualizado con las últimas publicaciones y actividades de nuestra comunidad.',
    'feed.comingSoon': '¡Contenido del feed próximamente! Aquí se mostrarán publicaciones, actualizaciones y actividades de la comunidad.',
    
    // About Page
    'about.title': 'Sobre Nuestra Empresa',
    'about.description': 'Conoce más sobre nuestra misión, valores y el equipo detrás de nuestras soluciones innovadoras.',
    'about.mission': 'Nuestra Misión',
    'about.missionText': 'Nos dedicamos a proporcionar soluciones tecnológicas de vanguardia que empoderan a empresas e individuos para alcanzar sus objetivos. Nuestro compromiso con la excelencia impulsa todo lo que hacemos.',
    'about.team': 'Nuestro Equipo',
    'about.teamText': 'Nuestro equipo diverso de expertos reúne años de experiencia en tecnología, diseño y servicio al cliente. Trabajamos colaborativamente para brindar la mejor experiencia posible a nuestros usuarios.',
    
    // Login Page
    'login.title': 'Iniciar Sesión',
    'login.email': 'Email:',
    'login.password': 'Contraseña:',
    'login.loginBtn': 'Iniciar Sesión',
    'login.noAccount': '¿No tienes una cuenta?',
    'login.registerHere': 'Regístrate aquí',
    
    // Register Page
    'register.title': 'Registrarse',
    'register.firstName': 'Nombre:',
    'register.lastName': 'Apellido:',
    'register.email': 'Email:',
    'register.password': 'Contraseña:',
    'register.confirmPassword': 'Confirmar Contraseña:',
    'register.registerBtn': 'Registrarse',
    'register.hasAccount': '¿Ya tienes una cuenta?',
    'register.loginHere': 'Inicia sesión aquí',
    
    // Form validation messages
    'validation.fillAllFields': 'Por favor, completa todos los campos',
    'validation.passwordsMismatch': 'Las contraseñas no coinciden',
    'validation.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
    'validation.loginDemo': 'La funcionalidad de inicio de sesión se implementaría aquí',
    'validation.registerDemo': 'La funcionalidad de registro se implementaría aquí',
    
    // Profile Page
    'profile.aboutMe': 'Acerca de Mí',
    'profile.details' : 'Detalles',
    'profile.interests': 'Intereses',
    'profile.contact': 'Contacto',
    'profile.leaveMessage': 'Dejar un mensaje',
    'profile.age': 'Edad',
    'profile.status': 'Estado',
    'profile.location': 'Ubicación',
    'profile.occupation': 'Ocupación',
    'profile.memberSince': 'Miembro desde',
    'profile.single': 'Soltero',
    'profile.webDeveloper': 'Desarrollador Web',
  // Relationship statuses (use keys as stable identifiers)
  'relationship.single': 'Soltero(a)',
  'relationship.situationship': 'Relación ambigua',
  'relationship.inRelationship': 'En una relación',
  'relationship.engaged': 'Comprometido(a)',
  'relationship.married': 'Casado(a)',
  'relationship.divorced': 'Divorciado(a)',
  'relationship.separated': 'Separado(a)',
  'relationship.widowed': 'Viudo(a)',
    
    // Profile Tabs
    'profile.kudos': 'Elogios',
    'profile.photos': 'Fotos',
    'profile.friends': 'Amigos',
    'profile.showMore': 'Mostrar Más',
    'profile.viewAll': 'Ver Todos',
  'profile.createNew': 'Crear Comunidad',
    'profile.totalPhotos': 'fotos en total',
  'profile.totalFriends': 'amigos',
    'profile.totalMembers': 'miembros',
  'profile.contact': 'Contacto',
  'profile.leaveMessage': 'Dejar un mensaje',
  'profile.message': 'Mensaje',
  'profile.opening': 'Abriendo...',
  'profile.unfriend': 'Eliminar Amistad',
  'profile.removing': 'Eliminando...',
  'profile.addFriend': 'Agregar Amigo',
  'profile.sending': 'Enviando...',
  'profile.edit': 'Editar',  // Gallery
  'gallery.backToProfile': '← Volver al perfil de {name}',
  'gallery.photosTitle': 'Fotos de {name}',
  'gallery.photosCount': '{count} fotos',
    
    // Community Model (public, member-only posting, join requests)
    'community.publicViewable': 'Cualquiera puede ver esta comunidad',
    'community.membersPost': 'Solo los miembros pueden publicar',
    'community.requestJoin': 'Solicitar unirse',
    'community.joinSent': 'Solicitud de unión enviada',
    'community.waitingApproval': 'Esperando aprobación',
    'community.youAreMember': 'Eres miembro',
    'community.postThread': 'Crear hilo',
    'community.join': 'Unirse',
    'community.leave': 'Salir',
    'community.joined': 'Participando',
    'community.notMember': 'No eres miembro',
    'community.membersOnly': 'Solo miembros',
    'community.approvalRequired': 'Se requiere aprobación para unirse',
    'community.joinError': 'No se pudo unir a la comunidad',
    'community.leaveError': 'No se pudo salir de la comunidad',
    'community.joinSuccess': 'Unido exitosamente',
    'community.leaveSuccess': 'Salida exitosa',
    
    // Status Indicators
    'status.online': 'En línea',
    'status.offline': 'Desconectado',
    'status.busy': 'Ocupado',
    'status.inactive': 'Inactivo',
    
    // Bio/About
    'profile.defaultBio': '¡Hola! Bienvenido a mi perfil.',
  'profile.birthday': 'Cumpleaños',
  'profile.communities': 'Comunidades',
    
    // Messaging
    'messages.hub': 'Mensajes',
    'messages.direct': 'Mensajes',
    'messages.groups': 'Chats Grupales',
    'messages.newMessage': 'Nuevo Mensaje',
    'messages.newConversation': 'Nueva conversación',
    'messages.newGroup': 'Nuevo grupo',
    'messages.searchMessages': 'Buscar mensajes...',
    'messages.typeMessage': 'Escribe un mensaje...',
    'messages.send': 'Enviar',
    'messages.loadingConversations': 'Cargando conversaciones...',
    'messages.noConversations': 'Aún no hay conversaciones',
    'messages.startConversation': 'Inicia una nueva conversación o crea un chat grupal',
    'messages.noMessages': 'Aún no hay mensajes',
    'messages.selectConversation': 'Selecciona una conversación para comenzar a enviar mensajes',
    'messages.groupName': 'Nombre del Grupo',
    'messages.groupNamePlaceholder': 'Ingresa el nombre del grupo...',
    'messages.selectMembers': 'Seleccionar Miembros',
    'messages.createGroup': 'Crear Grupo',
    'messages.cancel': 'Cancelar',
    'messages.search': 'Buscar...',
    'messages.selected': 'seleccionado(s)',
    'messages.loading': 'Cargando...',
    'messages.searchFriends': 'Buscar amigos...',
    'messages.noFriendsFound': 'No se encontraron amigos que coincidan con tu búsqueda',
    'messages.noFriendsYet': '¡Aún no hay amigos. Agrega amigos para comenzar a enviar mensajes!',
    'messages.searchToInvite': 'Buscar amigos para invitar...',
    'messages.noFriendsAvailable': 'No hay amigos disponibles',
    'messages.createNewGroup': 'Crear Nuevo Grupo',
    'messages.groupName': 'Nombre del Grupo',
    'messages.groupNamePlaceholder': 'Ingrese el nombre del grupo...',
    'messages.groupPhoto': 'Foto del Grupo (Opcional)',
    'messages.nextInviteFriends': 'Siguiente: Invitar Amigos',
    'messages.membersSelected': 'miembros seleccionados',
    'messages.memberSelected': 'miembro seleccionado',
    'messages.creating': 'Creando...',
    'messages.newMessage': 'Nuevo Mensaje',
    'messages.message': 'Mensaje',
    'messages.findFriends': 'Encontrar Amigos',
    
    // Time ago
    'time.justNow': 'justo ahora',
    'time.minuteAgo': 'minuto atrás',
    'time.minutesAgo': 'minutos atrás',
    'time.hourAgo': 'hora atrás',
    'time.hoursAgo': 'horas atrás',
    'time.dayAgo': 'día atrás',
    'time.daysAgo': 'días atrás',
    'time.weekAgo': 'semana atrás',
    'time.weeksAgo': 'semanas atrás',
    'time.monthAgo': 'mes atrás',
    'time.monthsAgo': 'meses atrás',
    'time.yearAgo': 'año atrás',
    'time.yearsAgo': 'años atrás',
    
    // About Page Tabs
    'about.tabs.about': 'Acerca de',
    'about.tabs.services': 'Servicios',
    'about.tabs.team': 'Equipo',
    
    // About Page Content
    'about.aboutUs': 'Sobre Nosotros',
    'about.description1': 'Bienvenido a nuestra red social. Social Trial es un ecosistema digital "vivo" que combina interacciones reales de usuarios con "mock-bots" que dan vida a tu feed y tus mensajes las 24 horas del día, los 7 días de la semana.',
    'about.ourServices': 'Nuestros Servicios',
    'about.service1': '🎨 Desarrollo Frontend Moderno con React & Next.js',
    'about.service2': '📱 Diseño Completamente Responsivo para Todos los Dispositivos',
    'about.service3': '🎯 Diseño Intuitivo de Interfaz y Experiencia de Usuario',
    'about.service4': '🤖 Integración de IA y Características en Tiempo Real',
    
    // User Profile Page
    'userProfile.memberSince': 'Miembro desde',
    'userProfile.about': 'Acerca de',
    'userProfile.bio': 'Bio',
    'userProfile.location': 'Ubicación',
    'userProfile.name': 'Nombre',
    'userProfile.avatar': 'URL del Avatar',
    'userProfile.editProfile': 'Editar Perfil',
    'userProfile.saveChanges': 'Guardar Cambios',
    'userProfile.cancel': 'Cancelar',
    'userProfile.activity': 'Actividad',
    'userProfile.posts': 'Publicaciones',
    'userProfile.favorites': 'Favoritos',
    'userProfile.following': 'Siguiendo',
    'userProfile.followers': 'Seguidores',
    'userProfile.recentActivity': 'Actividad Reciente',
    'userProfile.recent': 'Reciente',
    'userProfile.noRecentActivity': 'No hay actividad reciente para mostrar.',
    'userProfile.noPosts': '¡Aún no hay publicaciones. Comparte tu primer pensamiento!',
    'userProfile.noFavorites': '¡Aún no hay favoritos. Comienza a explorar y guarda contenido interesante!',
    'userProfile.bioPlaceholder': 'Cuéntanos sobre ti...',
    'userProfile.locationPlaceholder': '¿De dónde eres?',
    'userProfile.namePlaceholder': 'Tu nombre',
    
    // Feed Page
    'feed.createPostPlaceholder': '¿Qué estás pensando?',
    'feed.postButton': 'Publicar',
    'feed.loadingPosts': 'Cargando publicaciones...',
    'feed.noPosts': '¡Aún no hay publicaciones. Sé el primero en publicar algo!',
    'feed.reportPost': 'Denunciar Publicación',
    'feed.blockUser': 'Bloquear Usuario',
    'feed.hidePost': 'Ocultar Publicación',
    'feed.writeComment': 'Escribe un comentario...',
    'feed.reply': 'Responder',
    'feed.globalChat': 'Chat Global (Solo Usuarios)',
    'feed.botChat': 'Habla con nuestros Bots',
    'feed.typeMessage': 'Escribe un mensaje...',
    'feed.askBots': 'Pregunta a nuestros bots...',
    'feed.send': 'Enviar',
    'feed.reportMessage': 'Denunciar Mensaje',
    'feed.loadingMessages': 'Cargando mensajes...',
    'feed.noMessages': '¡Aún no hay mensajes. Inicia una conversación!',
    'feed.postTooLong': 'El contenido de la publicación debe tener 141 caracteres o menos',
    'feed.postCreated': '¡Publicación creada con éxito!',
    'feed.postFailed': 'Error al crear la publicación. Por favor, inténtalo de nuevo.',
    'feed.justNow': 'ahora mismo',
    'feed.minAgo': 'min atrás',
    'feed.hourAgo': 'hora atrás',
    'feed.hoursAgo': 'horas atrás',
    'feed.dayAgo': 'día atrás',
    'feed.daysAgo': 'días atrás',
    
    // Home Page Auth
    'home.login': 'Iniciar Sesión',
    'home.register': 'Registrarse',
    'home.email': 'Email',
    'home.password': 'Contraseña',
    'home.fullName': 'Nombre Completo',
    'home.confirmPassword': 'Confirmar Contraseña',
    'home.forgotPassword': '¿Olvidaste tu contraseña?',
    'home.loggingIn': 'Iniciando sesión...',
    'home.registering': 'Registrando...',
    'home.noAccount': '¿No tienes una cuenta?',
    'home.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'home.helloWelcome': '¡Hola, Bienvenido!',
    'home.welcomeBackTitle': '¡Bienvenido de Vuelta!',
    'home.noAccountRegister': '¿No tienes una cuenta? Regístrate o prueba nuestra Demo',
    'home.demo': 'Demo',
    'home.orLoginWith': 'o inicia sesión con otras plataformas sociales:',
    'home.orRegisterWith': 'o regístrate con otras plataformas sociales:',
    'home.accountCreated': '¡Cuenta creada con éxito! Por favor, inicia sesión con tus credenciales.',
    'home.demoLoginFailed': 'Error en el inicio de sesión demo. Por favor, inténtalo de nuevo.',
    
    // Friends
    'friends.title': 'Amigos',
    'friends.friendRequests': 'Solicitudes de Amistad',
    'friends.allFriends': 'Todos los Amigos',
    'friends.accept': 'Aceptar',
    'friends.decline': 'Rechazar',
    'friends.remove': 'Eliminar Amigo',
    'friends.noRequests': 'No hay solicitudes de amistad pendientes',
    'friends.noFriends': 'Aún no hay amigos',
    'friends.searchFriends': 'Buscar amigos...',
    'friends.showFriends': 'Mostrar Amigos',
    'friends.userFriends': 'Amigos de {name}',
    'friends.loading': 'Cargando amigos...',
    'friends.pending': 'Pendiente',
    'friends.accepted': 'Aceptado',
    'friends.addFriend': 'Agregar Amigo',
    'friends.unfriend': 'Dejar de ser Amigo',
    'friends.cancelRequest': 'Cancelar Solicitud',
    
    // Communities
    'communities.title': 'Comunidades',
    'communities.myCommu': 'Mis Comunidades',
    'communities.discover': 'Descubrir',
    'communities.create': 'Crear Comunidad',
    'communities.members': 'Miembros',
    'communities.posts': 'Publicaciones',
    'communities.noCommunities': 'Aún no hay comunidades',
    'communities.searchCommunities': 'Buscar comunidades...',
    'communities.allCategories': 'Todas las Categorías',
    'communities.loadingCommunities': 'Cargando comunidades...',
    'communities.noCommunitiesFound': 'No se encontraron comunidades',
    'communities.tryDifferentSearch': 'Intenta un término de búsqueda diferente.',
    'communities.join': 'Unirse',
    'communities.leave': 'Salir',
    'communities.noMembers': 'Aún no hay miembros',
    'communities.memberBadge': 'Miembro',
    'communities.adminBadge': 'Admin',
    'communities.moderatorBadge': 'Moderador',
    'communities.creatorBadge': 'Creador',
    'communities.previous': 'Anterior',
    'communities.next': 'Siguiente',
    'communities.pageOf': 'Página {page} de {total}',
    'communities.loadingThreads': 'Cargando hilos...',
    'communities.loadingThread': 'Cargando hilo...',
    'communities.communityThreads': 'Hilos de la Comunidad',
    'communities.newThread': 'Nuevo Hilo',
    'communities.noThreadsYet': 'Aún no hay hilos.',
    'communities.beFirstToDiscuss': '¡Sé el primero en iniciar una discusión!',
    'communities.createThread': 'Crear Nuevo Hilo',
    'communities.threadTitle': 'Título del Hilo',
    'communities.threadContent': 'Contenido',
    'communities.threadTitlePlaceholder': '¿Qué quieres discutir?',
    'communities.threadContentPlaceholder': 'Comparte tus pensamientos con la comunidad...',
    'communities.titleRequired': 'El título del hilo es obligatorio',
    'communities.titleTooShort': 'El título debe tener al menos 3 caracteres',
    'communities.titleTooLong': 'El título debe tener menos de 100 caracteres',
    'communities.contentRequired': 'El contenido del hilo es obligatorio',
    'communities.contentTooShort': 'El contenido debe tener al menos 10 caracteres',
    'communities.postThread': 'Publicar Hilo',
    'communities.cancel': 'Cancelar',
    'communities.reply': 'Responder',
    'communities.replies': 'Respuestas',
    'communities.writeReply': 'Escribe una respuesta...',
    'communities.postReply': 'Publicar Respuesta',
    'communities.failedToCreate': 'Error al crear la comunidad. Por favor, inténtalo de nuevo.',
    'communities.subtitle': 'Construye un espacio para que las personas se conecten y compartan',
    'communities.communityName': 'Nombre de la Comunidad',
    'communities.nameRequired': '*',
    'communities.namePlaceholder': 'Ingresa el nombre de la comunidad',
    'communities.aboutCommunity': 'Acerca de esta Comunidad',
    'communities.descriptionPlaceholder': 'Describe de qué trata tu comunidad...',
    'communities.categorySelect': 'Selecciona una categoría',
    'communities.privacySettings': 'Configuraciones de Privacidad',
    'communities.privateInviteOnly': 'Privada (Solo por invitación)',
    'communities.publicAnyone': 'Pública (Cualquiera puede unirse)',
    'communities.membersApproved': 'Los miembros deben ser aprobados antes de unirse',
    'communities.anyoneCanJoin': 'Cualquiera puede unirse a esta comunidad',
    'communities.creating': 'Creando...',
    'communities.createCommunity': 'Crear Comunidad',
    'communities.failedToLoad': 'Error al cargar la comunidad',
    'communities.failedToJoin': 'Error al unirse a la comunidad',
    'communities.failedToLeave': 'Error al salir de la comunidad',
    'communities.failedToCreateThread': 'Error al crear el hilo',
    'communities.threadNotFound': 'Hilo no encontrado',
    'communities.failedToLoadThread': 'Error al cargar el hilo',
    'communities.failedToUpdateLike': 'Error al actualizar me gusta',
    'communities.failedToAddComment': 'Error al agregar comentario',
    'communities.confirmDeleteComment': '¿Eliminar este comentario?',
    'communities.failedToDeleteComment': 'Error al eliminar comentario',
    'communities.confirmDeleteThread': '¿Eliminar este hilo? Esta acción no se puede deshacer.',
    'communities.failedToDeleteThread': 'Error al eliminar hilo',
    'communities.noCommentsYet': 'Aún no hay comentarios.',
    'communities.beFirstToComment': 'Aún no hay comentarios. ¡Sé el primero en comentar!',
    'communities.addComment': 'Agrega tu comentario...',
    'communities.postComment': 'Publicar Comentario',
    'communities.posting': 'Publicando...',
    'communities.confirmLeave': '¿Estás seguro de que quieres salir de esta comunidad?',
    'communities.categories': 'Categorías',
    'communities.created': 'Creado',
    'communities.about': 'Acerca de',
    'communities.threads': 'Hilos',
    'communities.administrators': 'Administradores',
    'communities.by': 'por',
    // Community Categories
    'category.technology': 'Tecnología',
    'category.gaming': 'Juegos',
    'category.music': 'Música',
    'category.sports': 'Deportes',
    'category.education': 'Educación',
    'category.entertainment': 'Entretenimiento',
    'category.lifestyle': 'Estilo de Vida',
    'category.business': 'Negocios',
    'category.health': 'Salud',
    'category.travel': 'Viajes',
    'category.food': 'Comida',
    'category.art': 'Arte',
    'category.other': 'Otros',
    
    // Marketplace
    'marketplace.title': 'Mercado',
    'marketplace.newProduct': 'Nuevo Producto',
    'marketplace.searchProducts': 'Buscar productos, categorías, vendedores...',
    'marketplace.search': 'Buscar',
    'marketplace.clearSearch': 'Limpiar Búsqueda',
    'marketplace.category': 'Categoría',
    'marketplace.price': 'Precio',
    'marketplace.condition': 'Condición',
    'marketplace.location': 'Ubicación',
    'marketplace.description': 'Descripción',
    'marketplace.contactSeller': 'Contactar Vendedor',
    'marketplace.contact': 'Contactar',
    'marketplace.noProducts': 'No hay productos disponibles',
    'marketplace.noProductsFound': 'No se encontraron productos',
    'marketplace.tryAdjusting': 'Intenta ajustar tu búsqueda o navega todos los productos',
    'marketplace.new': 'Nuevo',
    'marketplace.used': 'Usado',
    'marketplace.likeNew': 'Como Nuevo',
    'marketplace.good': 'Bueno',
    'marketplace.acceptable': 'Aceptable',
    'marketplace.outOfStock': 'Agotado',
    'marketplace.lowStock': 'Solo',
    'marketplace.left': 'restante',
    'marketplace.listProduct': 'Anunciar un Producto',
    'marketplace.listNewProduct': 'Anunciar Nuevo Producto',
    'marketplace.productName': 'Nombre del Producto',
    'marketplace.productDescription': 'Descripción del Producto',
    'marketplace.productPrice': 'Precio',
    'marketplace.productCondition': 'Condición',
    'marketplace.productCategory': 'Categoría',
    'marketplace.productLocation': 'Ubicación',
    'marketplace.uploadImages': 'Subir Imágenes',
    'marketplace.productImages': 'Imágenes del Producto',
    'marketplace.addImageUrl': 'Agregar URL de Imagen',
    'marketplace.imageUrl': 'URL de Imagen',
    'marketplace.invalidUrl': 'URL Inválida',
    'marketplace.primary': 'Principal',
    'marketplace.submit': 'Anunciar Producto',
    'marketplace.cancel': 'Cancelar',
    'marketplace.loading': 'Cargando productos...',
    'marketplace.loadingProduct': 'Cargando...',
    'marketplace.seller': 'Vendedor',
    'marketplace.soldBy': 'Vendido por',
    'marketplace.details': 'Detalles',
    'marketplace.noImage': 'Sin Imagen',
    'marketplace.addToFavorites': 'Agregar a favoritos',
    'marketplace.removeFromFavorites': 'Quitar de favoritos',
    'marketplace.reviews': 'reseñas',
    'marketplace.review': 'reseña',
    'marketplace.found': 'Encontrado',
    'marketplace.product': 'producto',
    'marketplace.products': 'productos',
    'marketplace.for': 'para',
    'marketplace.showing': 'Mostrando',
    'marketplace.loadMore': 'Cargar Más Productos',
    'marketplace.tryAgain': 'Intentar de Nuevo',
    'marketplace.failedToLoad': 'Error al cargar productos',
    'marketplace.quantity': 'Cantidad',
    'marketplace.available': 'disponible',
    'marketplace.addToCart': 'Agregar al Carrito',
    'marketplace.adding': 'Agregando...',
    'marketplace.addedToCart': '¡Agregado al carrito con éxito!',
    'marketplace.buyNow': 'Comprar Ahora',
    'marketplace.stockQuantity': 'Cantidad en Stock',
    'marketplace.required': '*',
    'marketplace.optional': '(Opcional)',
    'marketplace.enterProductName': 'Ingresa el nombre del producto',
    'marketplace.describeProduct': 'Describe tu producto en detalle...',
    'marketplace.shareItems': 'Comparte tus artículos con la comunidad',
    'marketplace.addUpTo5': 'Agrega hasta 5 URLs de imágenes para tu producto',
    'marketplace.selectCategories': 'Selecciona categorías que mejor describan tu producto',
    'marketplace.selected': 'seleccionado',
    'marketplace.categories': 'Categorías',
    'marketplace.listing': 'Anunciando...',
    'marketplace.outOfStockNotice': 'Este artículo está actualmente agotado',
    'marketplace.messagingComingSoon': '¡Función de mensajería próximamente!',
    
    // Gallery
    'gallery.title': 'Galería',
    'gallery.uploadPhoto': 'Subir Foto',
    'gallery.noPhotos': 'Aún no hay fotos',
    'gallery.delete': 'Eliminar',
    'gallery.addPhoto': 'Agregar Foto',
    'gallery.loadingPhotos': 'Cargando fotos...',
    'gallery.uploadFirst': '¡Sube tu primera foto para comenzar!',
    'gallery.uploadedOn': 'Subido el',
    'gallery.addNewPhoto': 'Agregar Nueva Foto',
    'gallery.selectPhoto': 'Haz clic para seleccionar una foto o arrastra y suelta',
    'gallery.fileTypes': 'PNG, JPG, GIF hasta 10MB',
    'gallery.changePhoto': 'Cambiar Foto',
    'gallery.caption': 'Leyenda (opcional)',
    'gallery.captionPlaceholder': 'Agrega una leyenda para tu foto...',
    'gallery.cancel': 'Cancelar',
    'gallery.uploading': 'Subiendo...',
    'gallery.uploadSuccess': '¡Foto "{caption}" subida con éxito!',
    'gallery.uploadFailed': 'Error al subir la foto. Por favor, inténtalo de nuevo.',
    'gallery.selectPhotoAlert': 'Por favor, selecciona una foto para subir',
    
    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.markAllRead': 'Marcar todas como leídas',
    'notifications.noNotifications': 'Aún no hay notificaciones',
    'notifications.viewAll': 'Ver todas las notificaciones',
    'notifications.justNow': 'justo ahora',
    'notifications.minutesAgo': 'hace {count}m',
    'notifications.hoursAgo': 'hace {count}h',
    'notifications.daysAgo': 'hace {count}d',
    
    // DevCard
    'devCard.role': 'Dev Full-Stack',
    'devCard.github': 'GitHub',
    'devCard.portfolio': 'Portafolio',
    'devCard.profile': 'Perfil',
    'devCard.description': 'Desarrollador detrás de este proyecto de red social, responsable de toda la arquitectura, implementación y despliegue de la aplicación. El proyecto fue construido con enfoque en escalabilidad, rendimiento y experiencia del usuario, integrando tecnologías modernas tanto en el frontend como en el backend.'
  }
};

export function LanguageProvider({ children }) {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    // Try to get saved language from localStorage, default to 'en'
    return localStorage.getItem('language') || 'en';
  });

  // Save language preference to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', currentLanguage);
  }, [currentLanguage]);

  const changeLanguage = (language) => {
    if (translations[language]) {
      setCurrentLanguage(language);
    }
  };

  const translate = (key, params = {}) => {
    let translation = translations[currentLanguage][key] || key;
    
    // Replace placeholders like {name}, {page}, {total}, etc.
    Object.keys(params).forEach(param => {
      translation = translation.replace(new RegExp(`\\{${param}\\}`, 'g'), params[param]);
    });
    
    return translation;
  };

  const value = {
    currentLanguage,
    changeLanguage,
    translate,
    availableLanguages: [
      { code: 'en', name: 'English' },
      { code: 'pt', name: 'Português' },
      { code: 'es', name: 'Español' }
    ]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    // Fallback to a no-op implementation to avoid runtime crashes when
    // components call useLanguage() outside of the provider (helps during
    // development). Log a warning so the issue can be tracked down.
    // Prefer fixing the provider placement in the app root, but this
    // defensive fallback keeps the UI usable.
    // eslint-disable-next-line no-console
    console.warn('useLanguage() was called outside of a LanguageProvider — returning fallback.');
    return {
      currentLanguage: 'en',
      changeLanguage: () => {},
      translate: (key) => key,
      availableLanguages: [
        { code: 'en', name: 'English' },
        { code: 'pt', name: 'Português' },
        { code: 'es', name: 'Español' }
      ]
    };
  }

  return context;
}